# Generated by Django 5.0.4 on 2024-05-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='photo',
            field=models.ImageField(default='23/01/20/', upload_to='questions/'),
            preserve_default=False,
        ),
    ]
