# Generated by Django 5.0.4 on 2024-05-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_question_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
